name: forex_companion
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  flutter_native_splash: ^2.4.7
  http: ^1.5.0
  fl_chart: ^1.1.1
  intl: ^0.20.2

  forexcompanion: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Remove this if youâ€™re using GoogleFonts instead
  # But if you still want local fallback fonts, you can keep it
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
